# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: sweeneyrobb
google_analytics: dbyll
permalink: /:categories/:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Sweeney Robb

description: Stylish Jekyll Theme
author:
  name: Robert Sweeney
  email: robert@sophcon.com
  github: sweeneyrobb
  twitter: sweeney_robb
  pinterest:
  linkedin: sweeneyrobb
  bio: Microsoft developer consultant. SharePoint and web technologies. C#, PowerShell, .NET. Automotive enthusiast (donations for Bugatti being taken).
  email_md5: 8e1d9d1f0c93726dd34defa6912799ea

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
